name: Build and Deploy

on:
  push:
    branches:
      - master  # Make sure this branch matches your branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package

      - name: Archive the JAR file
        uses: actions/upload-artifact@v3
        with:
          name: my-app
          path: target/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download the JAR file
        uses: actions/download-artifact@v3
        with:
          name: inventory

      - name: Deploy to Server
        run: |
          scp -o StrictHostKeyChecking=no target/*.jar ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/root/sxf-project/
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} 'supervisorctl restart your-app'
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}